//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCJMapper_V2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCJMapper_V2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _300i1 {
            get {
                object obj = ResourceManager.GetObject("_300i1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aurora {
            get {
                object obj = ResourceManager.GetObject("aurora", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cassini_Logo2_s {
            get {
                object obj = ResourceManager.GetObject("Cassini_Logo2_s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;profile  version=&quot;1&quot;  optionsVersion=&quot;2&quot;  rebindVersion=&quot;2&quot;  &gt;
        ///	&lt;platforms  &gt;
        ///		&lt;PC  keyboard=&quot;1&quot;  mouse=&quot;1&quot;  xboxpad=&quot;1&quot;  ps3pad=&quot;0&quot;  joystick=&quot;1&quot;  /&gt;
        ///		&lt;Xbox  keyboard=&quot;1&quot;  xboxpad=&quot;1&quot;  ps3pad=&quot;0&quot;  /&gt;
        ///		&lt;PS3  keyboard=&quot;1&quot;  xboxpad=&quot;0&quot;  ps3pad=&quot;1&quot;  /&gt;
        ///	&lt;/platforms&gt;
        ///
        ///	&lt;actiongroup  action=&quot;v_attack1&quot;  &gt;
        ///		&lt;action  name=&quot;v_attack1_group1&quot;  /&gt;
        ///		&lt;action  name=&quot;v_attack1_group2&quot;  /&gt;
        ///		&lt;action  name=&quot;v_attack1_group3&quot;  /&gt;
        ///	&lt;/actiongroup&gt;
        ///
        ///	&lt;ActivationModes  &gt;
        ///		&lt;ActivationMode  name=&quot;tap&quot;  onPres [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string defaultProfile {
            get {
                return ResourceManager.GetString("defaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hornet {
            get {
                object obj = ResourceManager.GetObject("hornet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Notes {
            get {
                object obj = ResourceManager.GetObject("Notes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YPR {
            get {
                object obj = ResourceManager.GetObject("YPR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
