//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCJMapper_V2.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SCJMapper_V2.Translation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string btAccept {
            get {
                return ResourceManager.GetString("btAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string btAssign {
            get {
                return ResourceManager.GetString("btAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        public static string btBlend {
            get {
                return ResourceManager.GetString("btBlend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btCancel {
            get {
                return ResourceManager.GetString("btCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Edits.
        /// </summary>
        public static string btCancelEdit {
            get {
                return ResourceManager.GetString("btCancelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string btClear {
            get {
                return ResourceManager.GetString("btClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        public static string btClearFilter {
            get {
                return ResourceManager.GetString("btClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to all axis.
        /// </summary>
        public static string btCopyToAllAxis {
            get {
                return ResourceManager.GetString("btCopyToAllAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all Unmapped.
        /// </summary>
        public static string btDisableUnmapped {
            get {
                return ResourceManager.GetString("btDisableUnmapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string btDone {
            get {
                return ResourceManager.GetString("btDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump XML.
        /// </summary>
        public static string btDump {
            get {
                return ResourceManager.GetString("btDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find 1st..
        /// </summary>
        public static string btFind {
            get {
                return ResourceManager.GetString("btFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab XML.
        /// </summary>
        public static string btGrab {
            get {
                return ResourceManager.GetString("btGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JS / Kbd.
        /// </summary>
        public static string btJsKbd {
            get {
                return ResourceManager.GetString("btJsKbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump and Save my Mapping.
        /// </summary>
        public static string btSaveMyMapping {
            get {
                return ResourceManager.GetString("btSaveMyMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        public static string btTogMonitor {
            get {
                return ResourceManager.GetString("btTogMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Edits.
        /// </summary>
        public static string btUpdateFromEdit {
            get {
                return ResourceManager.GetString("btUpdateFromEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string buttonExit {
            get {
                return ResourceManager.GetString("buttonExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch XML/Mapping tab automatically.
        /// </summary>
        public static string cbxAutoTabXML {
            get {
                return ResourceManager.GetString("cbxAutoTabXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CSV Listing.
        /// </summary>
        public static string cbxCSVListing {
            get {
                return ResourceManager.GetString("cbxCSVListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Gamepad.
        /// </summary>
        public static string cbxDetectGamepad {
            get {
                return ResourceManager.GetString("cbxDetectGamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Modifiers.
        /// </summary>
        public static string cbxListModifiers {
            get {
                return ResourceManager.GetString("cbxListModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamep.
        /// </summary>
        public static string cbxShowGamepad {
            get {
                return ResourceManager.GetString("cbxShowGamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick.
        /// </summary>
        public static string cbxShowJoystick {
            get {
                return ResourceManager.GetString("cbxShowJoystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyb..
        /// </summary>
        public static string cbxShowKeyboard {
            get {
                return ResourceManager.GetString("cbxShowKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapped.
        /// </summary>
        public static string cbxShowMappedOnly {
            get {
                return ResourceManager.GetString("cbxShowMappedOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string cbxShowMouse {
            get {
                return ResourceManager.GetString("cbxShowMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throttle.
        /// </summary>
        public static string cbxThrottle {
            get {
                return ResourceManager.GetString("cbxThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tree tips.
        /// </summary>
        public static string cbxTreeTips {
            get {
                return ResourceManager.GetString("cbxTreeTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit &quot;Disabled&quot;.
        /// </summary>
        public static string chkEditDisabled {
            get {
                return ResourceManager.GetString("chkEditDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string chkHideXX {
            get {
                return ResourceManager.GetString("chkHideXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor mouse axis.
        /// </summary>
        public static string chkMonitorMouse {
            get {
                return ResourceManager.GetString("chkMonitorMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List actions.
        /// </summary>
        public static string chkReport {
            get {
                return ResourceManager.GetString("chkReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Monitor.
        /// </summary>
        public static string FormDeviceMonitor {
            get {
                return ResourceManager.GetString("FormDeviceMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flight Device Tuning.
        /// </summary>
        public static string FormJSCalCurve {
            get {
                return ResourceManager.GetString("FormJSCalCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCJMapper - Options.
        /// </summary>
        public static string FormOptions {
            get {
                return ResourceManager.GetString("FormOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign Joystick Numbers.
        /// </summary>
        public static string FormReassign {
            get {
                return ResourceManager.GetString("FormReassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string FormSettings {
            get {
                return ResourceManager.GetString("FormSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actiontree as Table.
        /// </summary>
        public static string FormTable {
            get {
                return ResourceManager.GetString("FormTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Options ....
        /// </summary>
        public static string gbxAdvanced {
            get {
                return ResourceManager.GetString("gbxAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Capabilities.
        /// </summary>
        public static string gbxBoxCap {
            get {
                return ResourceManager.GetString("gbxBoxCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string gbxEditBindings {
            get {
                return ResourceManager.GetString("gbxEditBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string gbxFilters {
            get {
                return ResourceManager.GetString("gbxFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GamePad State.
        /// </summary>
        public static string gbxGBox {
            get {
                return ResourceManager.GetString("gbxGBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration - enter button numbers which should be ignored separated by spaces (e.g. 24 25).
        /// </summary>
        public static string gbxIgnoreBt {
            get {
                return ResourceManager.GetString("gbxIgnoreBt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Actionmaps - check the ones to hide.
        /// </summary>
        public static string gbxIgnoreMaps {
            get {
                return ResourceManager.GetString("gbxIgnoreMaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jsN - Assignment.
        /// </summary>
        public static string gbxJAssignment {
            get {
                return ResourceManager.GetString("gbxJAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick State.
        /// </summary>
        public static string gbxJBox {
            get {
                return ResourceManager.GetString("gbxJBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jsN - Assginment.
        /// </summary>
        public static string gbxReassignJS {
            get {
                return ResourceManager.GetString("gbxReassignJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Star Citizen Installation (e.g. C:\Games\StarCitizen).
        /// </summary>
        public static string gbxSCPath {
            get {
                return ResourceManager.GetString("gbxSCPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buttons:.
        /// </summary>
        public static string lB {
            get {
                return ResourceManager.GetString("lB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Filter:.
        /// </summary>
        public static string lblActionFilter {
            get {
                return ResourceManager.GetString("lblActionFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an option then click and drag.
        /// </summary>
        public static string lblChart {
            get {
                return ResourceManager.GetString("lblChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to damping.
        /// </summary>
        public static string lblDamp {
            get {
                return ResourceManager.GetString("lblDamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Def Bind Filter.
        /// </summary>
        public static string lblDefBindFilter {
            get {
                return ResourceManager.GetString("lblDefBindFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Ctrl.
        /// </summary>
        public static string lblDevCtrl {
            get {
                return ResourceManager.GetString("lblDevCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This device is listed as:.
        /// </summary>
        public static string lblJsnNumber {
            get {
                return ResourceManager.GetString("lblJsnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading data....
        /// </summary>
        public static string lblLoadingData {
            get {
                return ResourceManager.GetString("lblLoadingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping.
        /// </summary>
        public static string lblMapping {
            get {
                return ResourceManager.GetString("lblMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping name:.
        /// </summary>
        public static string lblMappingname {
            get {
                return ResourceManager.GetString("lblMappingname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Axis:.
        /// </summary>
        public static string lblNumAxes {
            get {
                return ResourceManager.GetString("lblNumAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Buttons:.
        /// </summary>
        public static string lblNumButtons {
            get {
                return ResourceManager.GetString("lblNumButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # DPad:.
        /// </summary>
        public static string lblNumDPad {
            get {
                return ResourceManager.GetString("lblNumDPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # POV:.
        /// </summary>
        public static string lblNumPOV {
            get {
                return ResourceManager.GetString("lblNumPOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # TSticks:.
        /// </summary>
        public static string lblNumSticks {
            get {
                return ResourceManager.GetString("lblNumSticks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Triggers:.
        /// </summary>
        public static string lblNumTriggers {
            get {
                return ResourceManager.GetString("lblNumTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Language:.
        /// </summary>
        public static string lblProfileLang {
            get {
                return ResourceManager.GetString("lblProfileLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string lblSelected {
            get {
                return ResourceManager.GetString("lblSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: Accepting changes will clear the action tree to apply the new settings; 
        ///Cancel now if you want to save your work first..
        /// </summary>
        public static string lblSettingNote {
            get {
                return ResourceManager.GetString("lblSettingNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec per 360° turn.
        /// </summary>
        public static string lblTurntime {
            get {
                return ResourceManager.GetString("lblTurntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usr Bind Filter.
        /// </summary>
        public static string lblUsrBindFilter {
            get {
                return ResourceManager.GetString("lblUsrBindFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For information and updates visit us @ Github ....
        /// </summary>
        public static string linkLblReleases {
            get {
                return ResourceManager.GetString("linkLblReleases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string mapAction {
            get {
                return ResourceManager.GetString("mapAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actionmap.
        /// </summary>
        public static string mapActionmap {
            get {
                return ResourceManager.GetString("mapActionmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Mode.
        /// </summary>
        public static string mapActivationMode {
            get {
                return ResourceManager.GetString("mapActivationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string mapDefault {
            get {
                return ResourceManager.GetString("mapDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions listed for input:.
        /// </summary>
        public static string mapHeader {
            get {
                return ResourceManager.GetString("mapHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string mapLocation {
            get {
                return ResourceManager.GetString("mapLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mapped.
        /// </summary>
        public static string mapMapped {
            get {
                return ResourceManager.GetString("mapMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified.
        /// </summary>
        public static string mapModified {
            get {
                return ResourceManager.GetString("mapModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string mapProfile {
            get {
                return ResourceManager.GetString("mapProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults, Load and Grab !.
        /// </summary>
        public static string meDefaultsLoadAndGrab {
            get {
                return ResourceManager.GetString("meDefaultsLoadAndGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Actiontree as XML.
        /// </summary>
        public static string meDumpActiontreeAsXML {
            get {
                return ResourceManager.GetString("meDumpActiontreeAsXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump DefaultProfile.
        /// </summary>
        public static string meDumpDefaultProfile {
            get {
                return ResourceManager.GetString("meDumpDefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Logfile.
        /// </summary>
        public static string meDumpLogfile {
            get {
                return ResourceManager.GetString("meDumpLogfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump Mapping List.
        /// </summary>
        public static string meDumpMappingList {
            get {
                return ResourceManager.GetString("meDumpMappingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Js Reassign Dialog....
        /// </summary>
        public static string meJsReassignDialog {
            get {
                return ResourceManager.GetString("meJsReassignDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load !.
        /// </summary>
        public static string meLoad {
            get {
                return ResourceManager.GetString("meLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load and Grab !.
        /// </summary>
        public static string meLoadAndGrab {
            get {
                return ResourceManager.GetString("meLoadAndGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset defaults !.
        /// </summary>
        public static string meResetDefaults {
            get {
                return ResourceManager.GetString("meResetDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset empty !.
        /// </summary>
        public static string meResetEmpty {
            get {
                return ResourceManager.GetString("meResetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset, Load and Grab !.
        /// </summary>
        public static string meResetLoadAndGrab {
            get {
                return ResourceManager.GetString("meResetLoadAndGrab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Dialog....
        /// </summary>
        public static string meSettingsDialog {
            get {
                return ResourceManager.GetString("meSettingsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Device Monitoring Dialog....
        /// </summary>
        public static string meShowDeviceMonitoringDialog {
            get {
                return ResourceManager.GetString("meShowDeviceMonitoringDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Device Tuning Dialog....
        /// </summary>
        public static string meShowDeviceTuningDialog {
            get {
                return ResourceManager.GetString("meShowDeviceTuningDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Options Dialog....
        /// </summary>
        public static string meShowOptionsDialog {
            get {
                return ResourceManager.GetString("meShowOptionsDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Toggle Table....
        /// </summary>
        public static string meShowToggleTable {
            get {
                return ResourceManager.GetString("meShowToggleTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config....
        /// </summary>
        public static string msBtConfig {
            get {
                return ResourceManager.GetString("msBtConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure the program.
        /// </summary>
        public static string msBtConfig_TT {
            get {
                return ResourceManager.GetString("msBtConfig_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dump....
        /// </summary>
        public static string msBtDump {
            get {
                return ResourceManager.GetString("msBtDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get additional information.
        /// </summary>
        public static string msBtDump_TT {
            get {
                return ResourceManager.GetString("msBtDump_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset....
        /// </summary>
        public static string msBtLoad {
            get {
                return ResourceManager.GetString("msBtLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset the action tree.
        /// </summary>
        public static string msBtLoad_TT {
            get {
                return ResourceManager.GetString("msBtLoad_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load....
        /// </summary>
        public static string msBtLoadMap {
            get {
                return ResourceManager.GetString("msBtLoadMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a map with options....
        /// </summary>
        public static string msBtLoadMap_TT {
            get {
                return ResourceManager.GetString("msBtLoadMap_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show....
        /// </summary>
        public static string msBtShow {
            get {
                return ResourceManager.GetString("msBtShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Options, Tuning and Tables.
        /// </summary>
        public static string msBtShow_TT {
            get {
                return ResourceManager.GetString("msBtShow_TT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exp.Value.
        /// </summary>
        public static string rbLivePtExponent {
            get {
                return ResourceManager.GetString("rbLivePtExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the SC Installation Path !!\nUse Settings to provide the path manually.
        /// </summary>
        public static string scpAutoPathFailed {
            get {
                return ResourceManager.GetString("scpAutoPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the SC Client Directory !!\n\nTried to look for:\n{0} \n\nPlease adjust the path in Settings\n.
        /// </summary>
        public static string scpClientDirNotFound {
            get {
                return ResourceManager.GetString("scpClientDirNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no vaild path given (empty string).
        /// </summary>
        public static string scpEmptyString {
            get {
                return ResourceManager.GetString("scpEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no vaild path given (invalid directory).
        /// </summary>
        public static string scpInvalidPath {
            get {
                return ResourceManager.GetString("scpInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the Star Citizen Installation.
        /// </summary>
        public static string setMsgBox {
            get {
                return ResourceManager.GetString("setMsgBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the Gamepad option needs a restart of the application !!.
        /// </summary>
        public static string setNote1 {
            get {
                return ResourceManager.GetString("setNote1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Notification.
        /// </summary>
        public static string setNote2 {
            get {
                return ResourceManager.GetString("setNote2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the same jsN was assigned to more than one Joystick - either fix it or exit with Cancel.
        /// </summary>
        public static string setNote3 {
            get {
                return ResourceManager.GetString("setNote3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Notification.
        /// </summary>
        public static string setNote4 {
            get {
                return ResourceManager.GetString("setNote4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string tActionText {
            get {
                return ResourceManager.GetString("tActionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addbind.
        /// </summary>
        public static string tAddBind {
            get {
                return ResourceManager.GetString("tAddBind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Def.Binding.
        /// </summary>
        public static string tDef_Binding {
            get {
                return ResourceManager.GetString("tDef_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Def.Modifier.
        /// </summary>
        public static string tDef_Modifier {
            get {
                return ResourceManager.GetString("tDef_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string tDevice {
            get {
                return ResourceManager.GetString("tDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mapping.
        /// </summary>
        public static string tdiAddBinding {
            get {
                return ResourceManager.GetString("tdiAddBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Mapping.
        /// </summary>
        public static string tdiAssignBinding {
            get {
                return ResourceManager.GetString("tdiAssignBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Mapping.
        /// </summary>
        public static string tdiBlendBinding {
            get {
                return ResourceManager.GetString("tdiBlendBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Mapping.
        /// </summary>
        public static string tdiClearBinding {
            get {
                return ResourceManager.GetString("tdiClearBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse to selected.
        /// </summary>
        public static string tdiCollapseAll {
            get {
                return ResourceManager.GetString("tdiCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Mapping.
        /// </summary>
        public static string tdiDelBinding {
            get {
                return ResourceManager.GetString("tdiDelBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all Mappings.
        /// </summary>
        public static string tdiExpandAll {
            get {
                return ResourceManager.GetString("tdiExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string tDisabled {
            get {
                return ResourceManager.GetString("tDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Activation Mode.
        /// </summary>
        public static string tdiTxDefActivationMode {
            get {
                return ResourceManager.GetString("tdiTxDefActivationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumps (XML, Logs etc.).
        /// </summary>
        public static string tPageDump {
            get {
                return ResourceManager.GetString("tPageDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Mappings.
        /// </summary>
        public static string tPageOther {
            get {
                return ResourceManager.GetString("tPageOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actionmap.
        /// </summary>
        public static string tREF_ActionMap {
            get {
                return ResourceManager.GetString("tREF_ActionMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string tsiCopy {
            get {
                return ResourceManager.GetString("tsiCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string tsiOpen {
            get {
                return ResourceManager.GetString("tsiOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string tsiPaste {
            get {
                return ResourceManager.GetString("tsiPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Replace all).
        /// </summary>
        public static string tsiPReplace {
            get {
                return ResourceManager.GetString("tsiPReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        public static string tsiSaveAs {
            get {
                return ResourceManager.GetString("tsiSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string tsiSelAll {
            get {
                return ResourceManager.GetString("tsiSelAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappings:.
        /// </summary>
        public static string tsLblMappings {
            get {
                return ResourceManager.GetString("tsLblMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile:.
        /// </summary>
        public static string tsLblProfile {
            get {
                return ResourceManager.GetString("tsLblProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        public static string tsLblSupportedProfile {
            get {
                return ResourceManager.GetString("tsLblSupportedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usr.Binding.
        /// </summary>
        public static string tUsr_Binding {
            get {
                return ResourceManager.GetString("tUsr_Binding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usr.Modifier.
        /// </summary>
        public static string tUsr_Modifier {
            get {
                return ResourceManager.GetString("tUsr_Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curve.
        /// </summary>
        public static string xCurve {
            get {
                return ResourceManager.GetString("xCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadzone.
        /// </summary>
        public static string xDeadzone {
            get {
                return ResourceManager.GetString("xDeadzone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev Control.
        /// </summary>
        public static string xDevControl {
            get {
                return ResourceManager.GetString("xDevControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Options.
        /// </summary>
        public static string xDeviceOptions {
            get {
                return ResourceManager.GetString("xDeviceOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent.
        /// </summary>
        public static string xExponent {
            get {
                return ResourceManager.GetString("xExponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamepad.
        /// </summary>
        public static string xGamepad {
            get {
                return ResourceManager.GetString("xGamepad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance.
        /// </summary>
        public static string xInstance {
            get {
                return ResourceManager.GetString("xInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invert.
        /// </summary>
        public static string xInvert {
            get {
                return ResourceManager.GetString("xInvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joystick.
        /// </summary>
        public static string xJoystick {
            get {
                return ResourceManager.GetString("xJoystick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard.
        /// </summary>
        public static string xKeyboard {
            get {
                return ResourceManager.GetString("xKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse.
        /// </summary>
        public static string xMouse {
            get {
                return ResourceManager.GetString("xMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string xNone {
            get {
                return ResourceManager.GetString("xNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string xOption {
            get {
                return ResourceManager.GetString("xOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 1:.
        /// </summary>
        public static string xPoint1 {
            get {
                return ResourceManager.GetString("xPoint1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 2:.
        /// </summary>
        public static string xPoint2 {
            get {
                return ResourceManager.GetString("xPoint2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Point 3:.
        /// </summary>
        public static string xPoint3 {
            get {
                return ResourceManager.GetString("xPoint3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation.
        /// </summary>
        public static string xSaturation {
            get {
                return ResourceManager.GetString("xSaturation", resourceCulture);
            }
        }
    }
}
